name: Checking

on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Setup repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2

      - name: Run linter
        run: deno lint

      - name: Run publish --dry-run
        run: deno publish --dry-run

      - name: Run tests
        run: deno test --quiet --coverage

      - name: Run Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: coverage/lcov.info
          use_oidc: true

