name: Publish JSR

on:
  push:
    branches:
      - main

jobs:

  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2

      - run: deno publish

